import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const seedData = [
  {
    "registrationDate": "2/3/26 7:06",
    "participantsName": "Aabir, Jana, Marala, Ira",
    "under15Participants": "2",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Aabir",
    "emailOrPhoneNo": "1794321138",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 001",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "2/3/26 11:53",
    "participantsName": "Ankhi/Russell/Borno/Shobdo",
    "under15Participants": "2",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Test",
    "emailOrPhoneNo": "17634361339",
    "transactionMode": "Cash",
    "amount": 0,
    "code": "HB 002",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "8/3/26 16:44",
    "participantsName": "Momin Mollah/ Khadija Tul Kovra/Mashrif Rayyaan Mollah",
    "under15Participants": "1",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Momin Mollah",
    "emailOrPhoneNo": "1794705734",
    "transactionMode": "",
    "amount": 0,
    "code": "HB 003",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "8/3/26 20:39",
    "participantsName": "Milon",
    "under15Participants": "0",
    "adultParticipants": "1",
    "transactionNoTransfereeName": "Milon",
    "emailOrPhoneNo": "milon_abdullah@yahoo.de",
    "transactionMode": "Cash",
    "amount": 0,
    "code": "HB 004",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "8/3/26 21:03",
    "participantsName": "Rukhsana/ kantom",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Rukhsana Dill- Riaz",
    "emailOrPhoneNo": "17683335399",
    "transactionMode": "On Spot",
    "amount": 0,
    "code": "HB 005",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "8/3/26 21:57",
    "participantsName": "Nusrat,mamun,umaima,fayaz",
    "under15Participants": "2",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Nusrat Yesmine urme",
    "emailOrPhoneNo": "nusrat20mamun@gmail.com",
    "transactionMode": "Bank",
    "amount": 5,
    "code": "HB 006",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "9/3/26 0:38",
    "participantsName": "Mushfiqul / Azima / Sanjida / Nazmul",
    "under15Participants": "0",
    "adultParticipants": "4",
    "transactionNoTransfereeName": "A B M Mushfiqul Huda",
    "emailOrPhoneNo": "mushfiqul.onee@gmail.com",
    "transactionMode": "Bank",
    "amount": 11,
    "code": "HB 007",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "9/3/26 5:51",
    "participantsName": "Haseeb",
    "under15Participants": "0",
    "adultParticipants": "1",
    "transactionNoTransfereeName": "Haseeb Mahmud",
    "emailOrPhoneNo": "17657860809",
    "transactionMode": "Paypal",
    "amount": 3,
    "code": "HB 008",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "9/3/26 8:13",
    "participantsName": "Arun",
    "under15Participants": "0",
    "adultParticipants": "1",
    "transactionNoTransfereeName": "Arun Chandra Roy",
    "emailOrPhoneNo": "4915215301436",
    "transactionMode": "",
    "amount": 0,
    "code": "HB 009",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "9/3/26 17:11",
    "participantsName": "Khalilur Rahman / Sultana Rahman",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "SULTANA RAHMAN",
    "emailOrPhoneNo": "krahman7755@googlemail.com",
    "transactionMode": "Bank",
    "amount": 0,
    "code": "HB 010",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "10/3/26 20:21",
    "participantsName": "Shaman & Tani",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Shaman Rahman",
    "emailOrPhoneNo": "1772937043",
    "transactionMode": "Paypal",
    "amount": 6,
    "code": "HB 011",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "11/3/26 20:03",
    "participantsName": "Tahmina Rahman/ Shafiur Rahman",
    "under15Participants": "1",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Md. Najrul Islam",
    "emailOrPhoneNo": "17657745612",
    "transactionMode": "Bank",
    "amount": 5,
    "code": "HB 012",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "11/3/26 22:09",
    "participantsName": "Riad / Anika / Abyad / Amayr",
    "under15Participants": "2",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Paypal Md Rokeybull Hasan",
    "emailOrPhoneNo": "17643382388",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 013",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "12/3/26 20:42",
    "participantsName": "Familie Shafiq",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "75R1120496400013C",
    "emailOrPhoneNo": "15771674590",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 014",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "3/16/2026 8:15:43",
    "participantsName": "Mitu/ Nizam/ Nusayba",
    "under15Participants": "1",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Nizam",
    "emailOrPhoneNo": "15156387714",
    "transactionMode": "Artist & Family",
    "amount": 0,
    "code": "HB 015",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "3/16/2026 11:03:21",
    "participantsName": "Manisha/Jony",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Manisha Das",
    "emailOrPhoneNo": "15510415680",
    "transactionMode": "Bank",
    "amount": 6,
    "code": "HB 016",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "3/16/2026 13:59:05",
    "participantsName": "Mohammed Moinuddin Mortuza - Nazifa Tahea",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "4GD83535TU107051S",
    "emailOrPhoneNo": "491728501157",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 017",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "3/17/2026 20:16:39",
    "participantsName": "Khandakar/sirmin/zahin",
    "under15Participants": "1",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Mohamed Shimul Khandakar",
    "emailOrPhoneNo": "17643293310",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 018",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "3/18/2026 7:30:59",
    "participantsName": "Fariza/David",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "6UR75799N7422661Y",
    "emailOrPhoneNo": "4917620965156",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 019",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "3/18/2026 23:39:59",
    "participantsName": "Nishat Ahmed Samrin and Md Mahmdul Hasan Suzan",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Nishat Ahmed Samrin",
    "emailOrPhoneNo": "+4915510 337638",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 020",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "3/19/2026 22:14:39",
    "participantsName": "Arka Bhattacharjee/Priya Acharjee/Projita Bhattacharjee",
    "under15Participants": "1",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "4SF896737X654822H",
    "emailOrPhoneNo": "15732625770",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 021",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "3/20/2026 14:36:34",
    "participantsName": "MD.Zia Uddin/Anika Musarrat",
    "under15Participants": "1",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "1GJ65167NS7638354",
    "emailOrPhoneNo": "17643288995",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 022",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "3/24/2026 12:33:40",
    "participantsName": "Mehedi, Aklima, Arhaan",
    "under15Participants": "1",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "7GN770665C912971B",
    "emailOrPhoneNo": "1783299888",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 023",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "3/24/2026 18:25:35",
    "participantsName": "Afrin, Tobias",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Afrin Sultana",
    "emailOrPhoneNo": "17662947275",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 024",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "3/24/2026 20:59:30",
    "participantsName": "Sampita Bhakta",
    "under15Participants": "0",
    "adultParticipants": "1",
    "transactionNoTransfereeName": "Artist",
    "emailOrPhoneNo": "raisampita3010@gmail.com",
    "transactionMode": "Artist",
    "amount": 0,
    "code": "HB 025",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "3/24/2026 21:08:33",
    "participantsName": "Ingo, Montasera, Maryam and Fatima",
    "under15Participants": "2",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Tutul Debnath",
    "emailOrPhoneNo": "ingoerichhoffmann@yahoo.de",
    "transactionMode": "Bank",
    "amount": 5,
    "code": "HB 026",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "3/24/2026 21:17:43",
    "participantsName": "Asif/Tahmina/Zafar",
    "under15Participants": "0",
    "adultParticipants": "3",
    "transactionNoTransfereeName": "M. Zafar Iqbal",
    "emailOrPhoneNo": "1794839331",
    "transactionMode": "Bank",
    "amount": 5,
    "code": "HB 027",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "3/26/2026 15:35:56",
    "participantsName": "Hasib(niloy) / Dorothea",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "03645680B72935912",
    "emailOrPhoneNo": "Hasib1994@live.con",
    "transactionMode": "Paypal",
    "amount": 6,
    "code": "HB 028",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "3/26/2026 19:22:01",
    "participantsName": "Abu Saleh Md Musa / Taslima Akter",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "9Y544518HU639563A",
    "emailOrPhoneNo": "puzzlemusa@gmail.com",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 029",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "3/26/2026 20:00:40",
    "participantsName": "Golam, Nusratun",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Md Golam Rabbani",
    "emailOrPhoneNo": "1792204405",
    "transactionMode": "Bank",
    "amount": 5,
    "code": "HB 030",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "3/27/2026 22:54:42",
    "participantsName": "Nazmus/Rajvia",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "9X9369689B6510424",
    "emailOrPhoneNo": "17660882980",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 031",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "3/29/2026 17:07:15",
    "participantsName": "Hasan, Riya",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Kamrul Hasan",
    "emailOrPhoneNo": "1789846353",
    "transactionMode": "Paypal",
    "amount": 6,
    "code": "HB 032",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "3/29/2026 20:34:16",
    "participantsName": "Fahad Galib / Naushin Zabin Antara / Ishrat Rezowana/ Faisal Arifin",
    "under15Participants": "0",
    "adultParticipants": "4",
    "transactionNoTransfereeName": "onifahad6@gmail.com",
    "emailOrPhoneNo": "15771362312",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 033",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "3/29/2026 21:09:59",
    "participantsName": "Md Risul Karim, Rafia Anjum, Rushayd Anjum Karim",
    "under15Participants": "1",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "mdrisulkarim@gmail.com",
    "emailOrPhoneNo": "1744528120",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 034",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "3/29/2026 22:04:47",
    "participantsName": "Shashi / Faron",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Shashi Karmaker",
    "emailOrPhoneNo": "shashikarmaker@gmail.com",
    "transactionMode": "Bank",
    "amount": 6,
    "code": "HB 035",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "3/29/2026 22:06:12",
    "participantsName": "Mohammad/Afrina/Ishtiyak",
    "under15Participants": "1",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Afrina Ferdousi Mitu",
    "emailOrPhoneNo": "+49 172 8870969",
    "transactionMode": "Bank",
    "amount": 5,
    "code": "HB 036",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "3/30/2026 0:18:29",
    "participantsName": "Md Mominul Islam/Nadia Akter/Nusaybah Ihana islam",
    "under15Participants": "1",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Md Mominul Islam",
    "emailOrPhoneNo": "1792410867",
    "transactionMode": "",
    "amount": 0,
    "code": "HB 037",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "3/30/2026 12:55:09",
    "participantsName": "Lipi/Sharaf",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Russell",
    "emailOrPhoneNo": "+49 178 1661371",
    "transactionMode": "On Spot",
    "amount": 0,
    "code": "HB 038",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "3/30/2026 18:42:44",
    "participantsName": "Somrita/Sriram",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "1MK934777B250933P",
    "emailOrPhoneNo": "1735369131",
    "transactionMode": "Paypal",
    "amount": 6,
    "code": "HB 039",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "3/30/2026 19:05:44",
    "participantsName": "Apurba K",
    "under15Participants": "0",
    "adultParticipants": "1",
    "transactionNoTransfereeName": "Apurba Kundu",
    "emailOrPhoneNo": "15560599760",
    "transactionMode": "Bank",
    "amount": 3,
    "code": "HB 040",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "3/30/2026 20:48:08",
    "participantsName": "Aniya, Kevin",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Aniya Azam Rakhi",
    "emailOrPhoneNo": "Aniya.azam63@gmail.com",
    "transactionMode": "Bank",
    "amount": 6,
    "code": "HB 041",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "3/31/2026 16:33:49",
    "participantsName": "Sabbir, Nisha, Shayaan",
    "under15Participants": "1",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "9X3211904N2578405",
    "emailOrPhoneNo": "sahmad29@outlook.com",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 042",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "3/31/2026 21:16:16",
    "participantsName": "Shamsur Nahar",
    "under15Participants": "0",
    "adultParticipants": "1",
    "transactionNoTransfereeName": "r-mohiuddin@gmx.de/ Rafida Mohiuddin",
    "emailOrPhoneNo": "r-mohiuddin@gmx.de",
    "transactionMode": "",
    "amount": 0,
    "code": "HB 043",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "1/4/26 0:21",
    "participantsName": "Kibria / Fariha",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Fariha Mawla",
    "emailOrPhoneNo": "Farihamawla189@gmail.com",
    "transactionMode": "Bank",
    "amount": 6,
    "code": "HB 044",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "1/4/26 1:00",
    "participantsName": "Imran/Nishat/Aiyaaz",
    "under15Participants": "1",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Md Imran Hossain",
    "emailOrPhoneNo": "biddutvhai@gmail.com",
    "transactionMode": "Bank",
    "amount": 5,
    "code": "HB 045",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "1/4/26 1:42",
    "participantsName": "Sajul Sikder",
    "under15Participants": "1",
    "adultParticipants": "1",
    "transactionNoTransfereeName": "Sajul Sikder",
    "emailOrPhoneNo": "1743870069",
    "transactionMode": "",
    "amount": 0,
    "code": "HB 046",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "1/4/26 23:14",
    "participantsName": "Sajul Sikder",
    "under15Participants": "0",
    "adultParticipants": "1",
    "transactionNoTransfereeName": "Sajul Sikder",
    "emailOrPhoneNo": "1743870069",
    "transactionMode": "",
    "amount": 0,
    "code": "HB 047",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "2/4/26 19:00",
    "participantsName": "Shaminaz Jabin / Shakif Malek",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "2B926941C12341311",
    "emailOrPhoneNo": "jahinjabin@gmail.com",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 048",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "3/4/26 6:31",
    "participantsName": "Rayhan / Farhin / Aideen",
    "under15Participants": "1",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Rayhan",
    "emailOrPhoneNo": "1638816709",
    "transactionMode": "Paypal",
    "amount": 6,
    "code": "HB 049",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "3/4/26 12:54",
    "participantsName": "Mou /Priyom",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Joyosri Das Mou",
    "emailOrPhoneNo": "491745309864",
    "transactionMode": "Stall",
    "amount": 0,
    "code": "HB 050",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "3/4/26 15:32",
    "participantsName": "Sinthia Hossain Farien/Marwa Noor",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "54H61128MA347902C",
    "emailOrPhoneNo": "Shfarien@gmail.com",
    "transactionMode": "Paypal",
    "amount": 6,
    "code": "HB 051",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "4/4/26 11:54",
    "participantsName": "Hasan Sarker / Saima Akter",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Paypal",
    "emailOrPhoneNo": "17634600563",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 052",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "4/4/26 22:18",
    "participantsName": "Volker Schaar , Martina Rehor",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "4BF342234M9242016",
    "emailOrPhoneNo": "1782130378",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 053",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "5/4/26 11:10",
    "participantsName": "Tazia/Arif/Aria",
    "under15Participants": "1",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "01F26773128758623",
    "emailOrPhoneNo": "1747791676",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 054",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "5/4/26 15:20",
    "participantsName": "Rakin & Tabi",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Tabia Hossain",
    "emailOrPhoneNo": "1725196317",
    "transactionMode": "Bank",
    "amount": 5,
    "code": "HB 055",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "5/4/26 19:11",
    "participantsName": "Mahlaqa, Ziad",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "0F091970C6245605J",
    "emailOrPhoneNo": "15906452050",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 056",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "5/4/26 23:44",
    "participantsName": "Nasrin / shepaet / Tanisha",
    "under15Participants": "1",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Shepaet Hossain",
    "emailOrPhoneNo": "4915214796352",
    "transactionMode": "",
    "amount": 0,
    "code": "HB 057",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "6/4/26 9:42",
    "participantsName": "Abdullahil Kafi (Kanchan)",
    "under15Participants": "0",
    "adultParticipants": "1",
    "transactionNoTransfereeName": "bangla@gmx.de",
    "emailOrPhoneNo": "0163 5510531",
    "transactionMode": "Paypal",
    "amount": 3,
    "code": "HB 058",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "6/4/26 11:03",
    "participantsName": "Shamshun Nahar/Lovely Ahmed/Layla Momin/Neha Bhuiyan/Kona Sadia/Nasrin Akhter/Dolly Hossain",
    "under15Participants": "0",
    "adultParticipants": "7",
    "transactionNoTransfereeName": "Bank",
    "emailOrPhoneNo": "Anika Vabi",
    "transactionMode": "Bank",
    "amount": 21,
    "code": "HB 059",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "6/4/26 18:29",
    "participantsName": "Mehedi+jui",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "8NR43961TJ931573Y",
    "emailOrPhoneNo": "17620484017",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 060",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "6/4/26 23:25",
    "participantsName": "Aminul",
    "under15Participants": "0",
    "adultParticipants": "1",
    "transactionNoTransfereeName": "Mohammad Asif Noor Tushar",
    "emailOrPhoneNo": "rlusa412@gmail.com",
    "transactionMode": "Bank",
    "amount": 3,
    "code": "HB 061",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "7/4/26 10:52",
    "participantsName": "Jabun nahar Moral",
    "under15Participants": "1",
    "adultParticipants": "1",
    "transactionNoTransfereeName": "Jabun nahar Moral",
    "emailOrPhoneNo": "4917661871869",
    "transactionMode": "",
    "amount": 0,
    "code": "HB 062",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "7/4/26 23:11",
    "participantsName": "Alayna, Medina, Anmol, Koli",
    "under15Participants": "3",
    "adultParticipants": "1",
    "transactionNoTransfereeName": "fahianbhuiyan@yahoo.com",
    "emailOrPhoneNo": "fahianbhuiyan@yahoo.com",
    "transactionMode": "",
    "amount": 0,
    "code": "HB 063",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "8/4/26 9:52",
    "participantsName": "Mollik/Ahmed",
    "under15Participants": "2",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Sabbir hossain mollik",
    "emailOrPhoneNo": "sabbirhossainit@gmail.com",
    "transactionMode": "Bank",
    "amount": 5,
    "code": "HB 064",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "8/4/26 18:14",
    "participantsName": "Mamun Ahsan Khan",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "57X30322KN2641801",
    "emailOrPhoneNo": "491712638499",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 065",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "8/4/26 22:56",
    "participantsName": "Tasnim Akon",
    "under15Participants": "0",
    "adultParticipants": "1",
    "transactionNoTransfereeName": "7HA11950MV246784Y",
    "emailOrPhoneNo": "491773831870",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 066",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "9/4/26 10:33",
    "participantsName": "Yusra/Nazia/Mushfeq",
    "under15Participants": "1",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "1DB79627LT4134822",
    "emailOrPhoneNo": "nazia.noordu@gmail.com",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 067",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "9/4/26 13:11",
    "participantsName": "Uttara, Shawrup",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Shawrup Kumer Suter",
    "emailOrPhoneNo": "15150539667",
    "transactionMode": "Bank",
    "amount": 5,
    "code": "HB 068",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "9/4/26 13:18",
    "participantsName": "Anita Vokta/Shikha Pramanik",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Russell/Shampita",
    "emailOrPhoneNo": "Shampita",
    "transactionMode": "Artist Family",
    "amount": 0,
    "code": "HB 069",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "9/4/26 16:54",
    "participantsName": "Mohd Istiak Ahmed",
    "under15Participants": "0",
    "adultParticipants": "1",
    "transactionNoTransfereeName": "6EG74380K8776420N",
    "emailOrPhoneNo": "4915738778802",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 070",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "9/4/26 17:01",
    "participantsName": "Mushfiqur Rahman, Shakibul Islam",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Mushfiqur Rahman, 79J04933H93187222",
    "emailOrPhoneNo": "bdbmhd@gmail.com",
    "transactionMode": "Paypal",
    "amount": 6,
    "code": "HB 071",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "9/4/26 17:01",
    "participantsName": "Azaher",
    "under15Participants": "0",
    "adultParticipants": "1",
    "transactionNoTransfereeName": "Md Azaher Rahman",
    "emailOrPhoneNo": "+49 176 62038555",
    "transactionMode": "Paypal",
    "amount": 3,
    "code": "HB 072",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "9/4/26 17:31",
    "participantsName": "Lota, Lilly, Ayaan, Rayyan,",
    "under15Participants": "2",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Lota Akter",
    "emailOrPhoneNo": "17632295576",
    "transactionMode": "Bank",
    "amount": 5,
    "code": "HB 073",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "9/4/26 17:38",
    "participantsName": "Lota, Lilly, Ayaan, Rayyan (Double Entry)",
    "under15Participants": "2",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Lota Akter",
    "emailOrPhoneNo": "017632295576 (lota.akter22@gmail.com)",
    "transactionMode": "Double Entry",
    "amount": 0,
    "code": "HB 074",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "9/4/26 18:36",
    "participantsName": "Abdullahil/Israt",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "15V66463H7752205X",
    "emailOrPhoneNo": "Kafiabdullahil96@gmail.com",
    "transactionMode": "Paypal",
    "amount": 0,
    "code": "HB 075",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "9/4/26 22:10",
    "participantsName": "Abir Bin Naushad(Volunteer) , Nusrat Jahan",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Abir Bin Naushad",
    "emailOrPhoneNo": "naushadnirab@yahoo.com",
    "transactionMode": "",
    "amount": 0,
    "code": "HB 076",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "9/4/26 22:17",
    "participantsName": "Sompa/Tonmoy",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Sompa Akhter",
    "emailOrPhoneNo": "Onusukuri28@gmail.com",
    "transactionMode": "",
    "amount": 0,
    "code": "HB 077",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "10/4/26 12:40",
    "participantsName": "Helal,Farjana,Zaara,Prithola",
    "under15Participants": "2",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Diganta Basak",
    "emailOrPhoneNo": "4917622798700",
    "transactionMode": "",
    "amount": 0,
    "code": "HB 078",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "10/4/26 13:20",
    "participantsName": "Umma Sabikun Nahar / Araf Hossain",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "DE04130400000354164600",
    "emailOrPhoneNo": "+49 163 4603695 / sabikunbonna@gmail.com",
    "transactionMode": "Bank",
    "amount": 6,
    "code": "HB 079",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "10/4/26 13:36",
    "participantsName": "Raahim/Nazifa/Nahwan",
    "under15Participants": "1",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "2R068740SU957462N",
    "emailOrPhoneNo": "raahim94@gmail.com",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 080",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "10/4/26 14:14",
    "participantsName": "Asad Noor Shuvo/ Samia Jahan/ Izaan/ Ilhan",
    "under15Participants": "2",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "4WT61832J49953527",
    "emailOrPhoneNo": "Shuvome00@yahoo.com",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 081",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "10/4/26 16:48",
    "participantsName": "Arif/Saima/Saifan/Roza",
    "under15Participants": "2",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Arifur Rahman Arif",
    "emailOrPhoneNo": "17621649289",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 082",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "10/4/26 17:40",
    "participantsName": "Samrat/Tania/Zohan",
    "under15Participants": "1",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "7CB28592BM960671N",
    "emailOrPhoneNo": "alamgir.samrat@gmail.com",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 083",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "10/4/26 22:13",
    "participantsName": "Effat",
    "under15Participants": "0",
    "adultParticipants": "1",
    "transactionNoTransfereeName": "06700284KF434415R",
    "emailOrPhoneNo": "491781884007",
    "transactionMode": "Paypal",
    "amount": 3,
    "code": "HB 084",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "10/4/26 23:00",
    "participantsName": "Fowaz",
    "under15Participants": "1",
    "adultParticipants": "1",
    "transactionNoTransfereeName": "N/A",
    "emailOrPhoneNo": "fowazkhan@gmail.com",
    "transactionMode": "",
    "amount": 0,
    "code": "HB 085",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "10/4/26 23:29",
    "participantsName": "Mijanur, Nayma, Iqra",
    "under15Participants": "1",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Md Mijanur Rahaman",
    "emailOrPhoneNo": "15214950473",
    "transactionMode": "",
    "amount": 0,
    "code": "HB 086",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "11/4/26 1:05",
    "participantsName": "Nazia, Afzal, Lana, Liam",
    "under15Participants": "2",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "2B737485K0383670X",
    "emailOrPhoneNo": "nh.nazia.hussain@gmail.com",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 087",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "11/4/26 3:28",
    "participantsName": "Akul vai/Anhar Vai/Hasina vabi",
    "under15Participants": "0",
    "adultParticipants": "7",
    "transactionNoTransfereeName": "uddin814@gmail.com",
    "emailOrPhoneNo": "15156387714",
    "transactionMode": "",
    "amount": 0,
    "code": "HB 088",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "11/4/26 3:30",
    "participantsName": "Swastika, Amit Vara",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "uddin814@gmail.com",
    "emailOrPhoneNo": "15156387714",
    "transactionMode": "",
    "amount": 0,
    "code": "HB 089",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "11/4/26 4:08",
    "participantsName": "Md Ashiqur",
    "under15Participants": "1",
    "adultParticipants": "1",
    "transactionNoTransfereeName": "Md Ashiqur Rahman",
    "emailOrPhoneNo": "ashiksoc4@gmail.com",
    "transactionMode": "",
    "amount": 0,
    "code": "HB 090",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "11/4/26 8:47",
    "participantsName": "Tasnova Iftasum",
    "under15Participants": "0",
    "adultParticipants": "1",
    "transactionNoTransfereeName": "Tasnova Iftasum",
    "emailOrPhoneNo": "tasnovaiftesum2001@gmail.com",
    "transactionMode": "",
    "amount": 0,
    "code": "HB 091",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "11/4/26 10:14",
    "participantsName": "Dipanjon Modak/ Manisha Deb",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Dipanjon Modak",
    "emailOrPhoneNo": "+49 176 80894804",
    "transactionMode": "Bank",
    "amount": 5,
    "code": "HB 092",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "11/4/26 13:12",
    "participantsName": "Sinthia",
    "under15Participants": "0",
    "adultParticipants": "1",
    "transactionNoTransfereeName": "Dyeoan Fatema Tuz Johura",
    "emailOrPhoneNo": "sinsinthu2182@gmail.com",
    "transactionMode": "Bank",
    "amount": 3,
    "code": "HB 093",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "11/4/26 13:15",
    "participantsName": "Jisan, Farhan, Bithi",
    "under15Participants": "1",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Jisan, cash 11.04.2026",
    "emailOrPhoneNo": "1792345708",
    "transactionMode": "",
    "amount": 0,
    "code": "HB 094",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "11/4/26 13:24",
    "participantsName": "Tanzia, Alexander, Nevan, Ava",
    "under15Participants": "1",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Tanzia Islam",
    "emailOrPhoneNo": "15777714157",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 095",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "11/4/26 16:03",
    "participantsName": "Md Mainul Hoque, Tura Jahan",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "6X0793087H9914820",
    "emailOrPhoneNo": "+49 152 17961538",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 096",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "11/4/26 17:08",
    "participantsName": "Md Mukter Hossain",
    "under15Participants": "0",
    "adultParticipants": "1",
    "transactionNoTransfereeName": "Md Mukter Hossain",
    "emailOrPhoneNo": "mukterhossain1004@gmail.com",
    "transactionMode": "",
    "amount": 0,
    "code": "HB 097",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "11/4/26 17:19",
    "participantsName": "Mohuya & Madhu",
    "under15Participants": "1",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Stall",
    "emailOrPhoneNo": "mohuya99@gmail.com",
    "transactionMode": "Stall",
    "amount": 0,
    "code": "HB 098",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "11/4/26 19:22",
    "participantsName": "Shumana",
    "under15Participants": "0",
    "adultParticipants": "1",
    "transactionNoTransfereeName": "Shumana Mostafa",
    "emailOrPhoneNo": "+49 170 6675381",
    "transactionMode": "",
    "amount": 0,
    "code": "HB 099",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "11/4/26 20:07",
    "participantsName": "Eaiman Shoshi / Mst Laboni Akter Juthi / Abdurrahman Shoshi",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "5EF26883000089646 / Eaiman Shoshi",
    "emailOrPhoneNo": "+4915159199660 / coolshoshi.cse@gmail.com",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 100",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "11/4/26 20:57",
    "participantsName": "Madhury Biswas, Hasibul Islam, Heinz",
    "under15Participants": "0",
    "adultParticipants": "3",
    "transactionNoTransfereeName": "Madhury Biswas Joya",
    "emailOrPhoneNo": "+491794305384, mbjoya9990@gmail.com",
    "transactionMode": "",
    "amount": 0,
    "code": "HB 101",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "11/4/26 21:22",
    "participantsName": "Masud khan+ Tanzina khanI",
    "under15Participants": "2",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Masuker Rahman khan",
    "emailOrPhoneNo": "17632326370",
    "transactionMode": "Bank",
    "amount": 5,
    "code": "HB 102",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "11/4/26 21:31",
    "participantsName": "Omrita/Rakib/Nayara",
    "under15Participants": "1",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "NayaraIslam",
    "emailOrPhoneNo": "nayaraislam@gmail.com",
    "transactionMode": "On Spot",
    "amount": 0,
    "code": "HB 103",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "11/4/26 21:34",
    "participantsName": "Opp + sadia",
    "under15Participants": "2",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Masuker Rahmen khan",
    "emailOrPhoneNo": "17632326370",
    "transactionMode": "Bank",
    "amount": 5,
    "code": "HB 104",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "11/4/26 21:36",
    "participantsName": "Babul sharker",
    "under15Participants": "0",
    "adultParticipants": "1",
    "transactionNoTransfereeName": "Masuker Rahmen khan",
    "emailOrPhoneNo": "17632326370",
    "transactionMode": "Bank",
    "amount": 3,
    "code": "HB 105",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "11/4/26 21:43",
    "participantsName": "Md Tawhid Hossain, Ummehani Hassi, Mrinmoy Hossain",
    "under15Participants": "1",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Md Tawhid Hossain",
    "emailOrPhoneNo": "tawhidhossain13@gmail.com",
    "transactionMode": "",
    "amount": 0,
    "code": "HB 106",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "11/4/26 22:13",
    "participantsName": "Madhury Biswas, Hasibul Islam, Heinz",
    "under15Participants": "0",
    "adultParticipants": "3",
    "transactionNoTransfereeName": "Madhury Biswas Joya",
    "emailOrPhoneNo": "Double Registration See B102",
    "transactionMode": "",
    "amount": 0,
    "code": "HB 107",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "11/4/26 22:39",
    "participantsName": "Md Billal Mia, Rijwana",
    "under15Participants": "1",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Sponsor",
    "emailOrPhoneNo": "17684658690",
    "transactionMode": "Sponsor",
    "amount": 0,
    "code": "HB 108",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "11/4/26 22:41",
    "participantsName": "Farhana Shefat, Md Al Amin",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Shefat1908@gmail.com",
    "emailOrPhoneNo": "Shefat1908@gmail.com",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 109",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "12/4/26 5:39",
    "participantsName": "Tamanna, Miah",
    "under15Participants": "0",
    "adultParticipants": "3",
    "transactionNoTransfereeName": "Tamanna Miah",
    "emailOrPhoneNo": "tamanna.miah@gmx.de",
    "transactionMode": "Paypal",
    "amount": 9,
    "code": "HB 110",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "12/4/26 10:52",
    "participantsName": "Bipasha, Debalin, Debosmita",
    "under15Participants": "1",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "86C52555XF249880M/Bipasha Nandi Jui",
    "emailOrPhoneNo": "Debalinroy83@gmail.com",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 111",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "12/4/26 13:20",
    "participantsName": "Toriqul, Aysha, Aleks, Matija",
    "under15Participants": "0",
    "adultParticipants": "4",
    "transactionNoTransfereeName": "Md Toriqul Islam",
    "emailOrPhoneNo": "4917697736541",
    "transactionMode": "Paypal",
    "amount": 0,
    "code": "HB 112",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "12/4/26 13:47",
    "participantsName": "Pranti Tawheed",
    "under15Participants": "0",
    "adultParticipants": "1",
    "transactionNoTransfereeName": "Pranti Tawheed",
    "emailOrPhoneNo": "15215730199",
    "transactionMode": "",
    "amount": 0,
    "code": "HB 113",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "12/4/26 14:33",
    "participantsName": "Chowdhury Mazdus/Nabila Mahbub/Mahdia Yashra",
    "under15Participants": "1",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "7P021737JX9928343",
    "emailOrPhoneNo": "safwanlmu@gmail.com",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 114",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "12/4/26 18:21",
    "participantsName": "Md Tajul Islam",
    "under15Participants": "0",
    "adultParticipants": "1",
    "transactionNoTransfereeName": "5XG81466GG3710129",
    "emailOrPhoneNo": "tajul.tuc@gmail.com",
    "transactionMode": "Paypal",
    "amount": 3,
    "code": "HB 115",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "12/4/26 18:54",
    "participantsName": "Rocksana Reza Lia",
    "under15Participants": "1",
    "adultParticipants": "1",
    "transactionNoTransfereeName": "Rocksana Reza Lia",
    "emailOrPhoneNo": "rocksanalia@gmail.com",
    "transactionMode": "Bank",
    "amount": 3,
    "code": "HB 116",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "12/4/26 18:58",
    "participantsName": "Mijan, nayma, iqra",
    "under15Participants": "1",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Mijanur Rahaman",
    "emailOrPhoneNo": "15214950473",
    "transactionMode": "",
    "amount": 0,
    "code": "HB 117",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "12/4/26 19:02",
    "participantsName": "Ziaur Rahman/Dilruba Akter/Aira Rahman/ayesha Rahman",
    "under15Participants": "2",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Ziaur Rahman",
    "emailOrPhoneNo": "1722799011",
    "transactionMode": "Bank",
    "amount": 5,
    "code": "HB 118",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "12/4/26 19:04",
    "participantsName": "Mahi/Beauty/Maioum/Fatima",
    "under15Participants": "4",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Mahi Uddin",
    "emailOrPhoneNo": "17671653737",
    "transactionMode": "Bank",
    "amount": 5,
    "code": "HB 119",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "12/4/26 19:05",
    "participantsName": "Spice Bazaar By Abnar",
    "under15Participants": "2",
    "adultParticipants": "8",
    "transactionNoTransfereeName": "Md Mofazzal Hossain",
    "emailOrPhoneNo": "15758877893",
    "transactionMode": "Paypal",
    "amount": 20,
    "code": "HB 120",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "12/4/26 19:08",
    "participantsName": "Pranab /Trisha / Oishani",
    "under15Participants": "1",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "3BD55856MT0858056 / Pranab kumar Pramanik",
    "emailOrPhoneNo": "+4915229495908, dr.pranab@ymail.com",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 121",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "12/4/26 19:09",
    "participantsName": "Goutom / Oni",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Goutom Dey",
    "emailOrPhoneNo": "infiniteme321@gmail.com",
    "transactionMode": "",
    "amount": 0,
    "code": "HB 122",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "12/4/26 19:10",
    "participantsName": "Israt",
    "under15Participants": "0",
    "adultParticipants": "1",
    "transactionNoTransfereeName": "Israt Jahan(commerzbank)",
    "emailOrPhoneNo": "15221332841",
    "transactionMode": "Bank",
    "amount": 3,
    "code": "HB 123",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "12/4/26 19:24",
    "participantsName": "Mijanur, Nayma, iqra (Double Entry See 118)",
    "under15Participants": "1",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Md Mijanur Rahaman . DE9 8541 00",
    "emailOrPhoneNo": "15214950473",
    "transactionMode": "Double Entry",
    "amount": 0,
    "code": "HB 124",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "12/4/26 19:33",
    "participantsName": "Moushumee, Abdullah",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Moushumee Rodela",
    "emailOrPhoneNo": "moushumee.rodela.tuli@gmail.com",
    "transactionMode": "",
    "amount": 0,
    "code": "HB 125",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "12/4/26 19:54",
    "participantsName": "Israt Jahan Surovi, Tayeb Muhtadi Oheen",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "suroviedu@gmail.com (oheen,surovi)",
    "emailOrPhoneNo": "suroviedu@gmail.com",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 126",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "12/4/26 20:08",
    "participantsName": "Lutful vai/Nuri Apa",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Paypal kanchan",
    "emailOrPhoneNo": "Lutful vai",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 127",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "12/4/26 20:08",
    "participantsName": "Raduan Sarif",
    "under15Participants": "0",
    "adultParticipants": "1",
    "transactionNoTransfereeName": "22145447B2392551M",
    "emailOrPhoneNo": "4917657915051",
    "transactionMode": "Paypal",
    "amount": 3,
    "code": "HB 128",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "12/4/26 20:09",
    "participantsName": "Israt Jahan, Tayeb Muhtadi",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "0BU12798MU704010S",
    "emailOrPhoneNo": "15774993219",
    "transactionMode": "Paypal",
    "amount": 8,
    "code": "HB 129",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "12/4/26 20:09",
    "participantsName": "Abanty Jaman Prity",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "92E37818RM7918811 / Abanty Jaman Prity",
    "emailOrPhoneNo": "1776037002",
    "transactionMode": "Paypal",
    "amount": 6,
    "code": "HB 130",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "12/4/26 20:15",
    "participantsName": "Tasnuva , Md Mubtahiz",
    "under15Participants": "1",
    "adultParticipants": "1",
    "transactionNoTransfereeName": "Tasnuva Tazrin",
    "emailOrPhoneNo": "4917614694008",
    "transactionMode": "",
    "amount": 0,
    "code": "HB 131",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "12/4/26 20:34",
    "participantsName": "Younus Khan,Rifat Ara Marjahan,Anabia Tasnim Khan , M A Hasib Khan",
    "under15Participants": "2",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "YOUNUS KHAN",
    "emailOrPhoneNo": "+49 179 4362786",
    "transactionMode": "Bank",
    "amount": 5,
    "code": "HB 132",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "12/4/26 20:37",
    "participantsName": "Amira",
    "under15Participants": "1",
    "adultParticipants": "1",
    "transactionNoTransfereeName": "Amira mostafa",
    "emailOrPhoneNo": "15566378147",
    "transactionMode": "",
    "amount": 0,
    "code": "HB 133",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "12/4/26 20:38",
    "participantsName": "Rajon / Amita",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "11024496W4405941K /Abdul Monnaf",
    "emailOrPhoneNo": "rajon@tuta.io",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 134",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "12/4/26 20:51",
    "participantsName": "Suman, Kunal, Sushmita, Ishvika, Shivika",
    "under15Participants": "2",
    "adultParticipants": "3",
    "transactionNoTransfereeName": "8VE69115B2658934X",
    "emailOrPhoneNo": "15166950420",
    "transactionMode": "Paypal",
    "amount": 8,
    "code": "HB 135",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "12/4/26 21:02",
    "participantsName": "Arijit , Sarani",
    "under15Participants": "1",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Arijit Paul",
    "emailOrPhoneNo": "Paul.bavaria@gmail.com",
    "transactionMode": "",
    "amount": 0,
    "code": "HB 136",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "12/4/26 21:10",
    "participantsName": "Amina, Tauhidul",
    "under15Participants": "0",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "5FF15918XP198084H/Mohammad Tahmid Islam",
    "emailOrPhoneNo": "15152004059",
    "transactionMode": "Paypal",
    "amount": 6,
    "code": "HB 137",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "12/4/26 21:13",
    "participantsName": "Mohammad, Emo, Shehzad, Hasan,Nishat,Arisa,Jubair, Fatema, Zayan",
    "under15Participants": "3",
    "adultParticipants": "6",
    "transactionNoTransfereeName": "Mohammad Noor Alam",
    "emailOrPhoneNo": "0176 63373918",
    "transactionMode": "",
    "amount": 0,
    "code": "HB 138",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "12/4/26 21:30",
    "participantsName": "Tanvir, Asfath, Alaina",
    "under15Participants": "1",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "Tanvir Hasan",
    "emailOrPhoneNo": "15753659434",
    "transactionMode": "Bank",
    "amount": 5,
    "code": "HB 139",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "12/4/26 21:55",
    "participantsName": "Ashfaqul, Maksura, Mivan, Arvin",
    "under15Participants": "2",
    "adultParticipants": "2",
    "transactionNoTransfereeName": "0JM01633NE870163V",
    "emailOrPhoneNo": "Ashfaqul.haque.cse@gmail.com",
    "transactionMode": "Paypal",
    "amount": 5,
    "code": "HB 140",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "12/4/26 23:12",
    "participantsName": "Nusrat kabir",
    "under15Participants": "0",
    "adultParticipants": "1",
    "transactionNoTransfereeName": "Nusrat kabir",
    "emailOrPhoneNo": "15772434353",
    "transactionMode": "",
    "amount": 0,
    "code": "HB 141",
    "isPresent": false,
    "isOnSpotRegistration": false
  },
  {
    "registrationDate": "12/4/26 23:59",
    "participantsName": "Nahida,urmi,aittizzo",
    "under15Participants": "0",
    "adultParticipants": "3",
    "transactionNoTransfereeName": "Bank",
    "emailOrPhoneNo": "nahidaislam2070@gmail.com",
    "transactionMode": "",
    "amount": 9,
    "code": "HB 143",
    "isPresent": false,
    "isOnSpotRegistration": false
  }
]

async function main() {
  const existing = await prisma.attendee.count()
  if (existing > 0) {
    console.log(`Database already has ${existing} records — skipping seed.`)
    return
  }

  console.log(`Seeding ${seedData.length} attendees…`)

  await prisma.attendee.createMany({
    data: seedData.map((row, i) => ({
      attendeeNo:                  i + 1,
      code:                        row.code,
      registrationDate:            row.registrationDate,
      participantsName:            row.participantsName,
      under15Participants:         parseInt(String(row.under15Participants), 10) || 0,
      adultParticipants:           parseInt(String(row.adultParticipants), 10) || 0,
      transactionNoTransfereeName: row.transactionNoTransfereeName,
      emailOrPhoneNo:              row.emailOrPhoneNo,
      transactionMode:             row.transactionMode,
      amount:                      typeof row.amount === 'number' ? row.amount : (parseFloat(String(row.amount)) || 0),
      isPresent:                   row.isPresent,
      isOnSpotRegistration:        false,
    })),
  })

  console.log(`✅ Seeded ${seedData.length} attendees.`)
}

main()
  .catch(e => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
